[pytest]
filterwarnings =
    ignore:urllib3 v2 only supports OpenSSL 1.1.1\+:Warning
    ignore:Please use `import python_multipart` instead\.:PendingDeprecationWarning:starlette\.formparsers
    ignore:builtin type SwigPyPacked has no __module__ attribute:DeprecationWarning
    ignore:builtin type SwigPyObject has no __module__ attribute:DeprecationWarning
    ignore:builtin type swigvarlink has no __module__ attribute:DeprecationWarning
    ignore:Support for class-based `config` is deprecated, use ConfigDict instead\.:DeprecationWarning:config\.config
